### ISSUE TITLE
how to increase the number of connections in postgres in kubernetes

### ISSUE THREAD

**Issue by nbabured** [GoogleCloudPlatform/postgresql-docker#34]
how to increase the number of connections in postgres in kubernetes

**Comment by cgn170** [comment]
You have different ways to increase the number of connections in postgresql inside kubernetes, you can do it "live" with the follow command using a postgresql client: 

psql > alter system set max_connections = 30;

Or if you want a fixed solution for the deployment you can add the follow environment variable to a configmap or directly to the container to overwrite the default configuration of postgresql. 

```yaml
env:
- name: "PGOPTIONS"
  value: "-c max_connections=30"
```

Regards
