### ISSUE TITLE
Recent major versions ? 

### ISSUE THREAD

**Issue by vadius45** [GoogleCloudPlatform/postgresql-docker#70]
Hello,
Any chance to offer PostgreSQL 12 and 13 soonish ? 
Thx

**Comment by armandomiani** [comment]
Hello @vadius45 ,

We will prioritize this upgrade for this month. 👍🏻 

Best

**Comment by armandomiani** [comment]
PR created: https://github.com/GoogleCloudPlatform/postgresql-docker/pull/72

**Comment by armandomiani** [comment]
@vadius45 , new versions 12 and 13 have been published to marketplace.gcr.io. You can pull them through the commands below:

```shell
gcloud auth configure-docker 
docker pull marketplace.gcr.io/google/postgresql13:latest
docker pull marketplace.gcr.io/google/postgresql12:latest
```

Thanks,

**Comment by vadius45** [comment]
all good, thanks a lot @armandomiani
